version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: nguyennt63
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_scripts:/opt/rabbitmq_scripts
    command: >
      sh -c "rabbitmq-server start && rabbitmqctl add_user user password &&
             rabbitmqctl set_user_tags user administrator &&
             rabbitmqctl set_permissions -p my_vhost user '.*' '.*' '.*' &&
             rabbitmqctl stop && tail -f /dev/null"
